spring:
  datasource: #独立quartz配置
    username: root
    password: 123456
    url: jdbc:mysql://110.40.253.205:3306/quartz
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      #      enabled: false 如果没有建表可以先打开这个配置禁用多数据源,自动建quartz表
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test;MODE=MySQL
          driver-class-name: org.h2.Driver
        quartz: #把quartz数据源也作为动态数据源的一个数据源
          username: root
          password: 123456
          url: jdbc:mysql://110.40.253.205:3306/quartz
          driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always


logging:
  level:
    com.baomidou: debug